### ISSUE TITLE
accomplish constant capture/neutralization time

### ISSUE THREAD

**Issue by The0zzy** [The0zzy/bf2042-portal-experience-frontlines#13]
Currently there is a built-in multiplier which influences capture/neutralization time of a capture point depending on the amount of people on spot. The goal is to achieve a constant/static capture/neutralization time regardless of the amount of people on the spot.

**Comment by The0zzy** [comment]
currently implemented by setting a higher capture time according to following function:
built-in-capture-multiplier: 1.5/x [x=amount of players capturing]
base-capture-time: 60s
adapted-capture-time: base-capture-time * ( 1 / (1.5/x))

**Comment by Manc0ur** [comment]
Find out if we set the capture time to the proposed 2 minutes, how this effects capture times with 1 to 10 players on all different objectives on the current maps (25).

**Comment by The0zzy** [comment]
mission accomplished!
Experimental capture time analysis can be found here: 
https://docs.google.com/spreadsheets/d/1HWzD_0yfyk1fxAUMesey-1QpNb-HfSZAtnxghyOZy4A/edit#gid=120610707
