### ISSUE TITLE
User interface and sounds

### ISSUE THREAD

**Issue by Manc0ur** [The0zzy/bf2042-portal-experience-frontlines#2]
**UI**
- [x] Place flag world icons above each objective flagpole
- [x] Place a timer in the text above each flag icon showing the time left to defend/attack
- [x] Set the world icon ownership to the corresponding team

**Sounds**
- [ ] Add a sound for when the next objective is shown
- [ ] Add a sound for when an objective is open for capturing
- [ ] Add a sound for when an objective is lost / failed to arm both bombs
- [ ] Add a sound for when an objective is captured

**Comment by The0zzy** [comment]
split into separate issues for better tracking
