### ISSUE TITLE
Test EnableHQ for better MCOM placements 

### ISSUE THREAD

**Issue by The0zzy** [The0zzy/bf2042-portal-experience-frontlines#21]
Right now mcoms are placed at the edge of the valid play area. By enabling the HQ area, the placements could be better or more equivalent in terms of spawn locations.

**Comment by Manc0ur** [comment]
Still not sure if EnableHQ will allow the enemy team to freely move into your HQ area. Doubt it tbh.

**Comment by The0zzy** [comment]
learned from BattlefieldDad, that this block is rather for disabling an HQ - means disabling the deployment and removing the restricted area. So, no option for our intention.
