### ISSUE TITLE
Player amount, balance and gameplay

### ISSUE THREAD

**Issue by Manc0ur** [The0zzy/bf2042-portal-experience-frontlines#3]
- [ ] Test gameplay with 12v12 and 16v16 players
- [ ] Test gameplay with the following vehicle setup: 1x MAV, 2x LATV-4 Recon and 1 Nightbird per team
- [ ] Set downed player state to downed in stead of crawling

**Comment by The0zzy** [comment]
split into specific issues for better tracking
