### ISSUE TITLE
better status message visualization

### ISSUE THREAD

**Issue by The0zzy** [The0zzy/bf2042-portal-experience-frontlines#33]
Current Version:
YOU-MCOMs-1-2-3-4-5->[MCOMs]<-ENEMY
YOU-MCOMs-1-2->[3]<-4-5-MCOMs-ENEMY

Alternatives:
ALLY > MCOMS •• | ✓ ✓ [¤] × × | •• MCOMS < ENEMY

YOU ► MCOMS •• | ✓ ✓ [¤] × × | •• MCOMS ◄ ENEMY

YOU | MCOMS • ✓ • ✓ • [¤] • × • × • MCOMS | ENEMY

YOU | MCOMS • ✓ ✓ <[¤]> × × • MCOMS | ENEMY

YOU | MCOMS • ✓-✓-✓-<[O]>-× • MCOMS | ENEMY
YOU | MCOMS • ✓-✓-✓-✓-✓ • <[MCOMS]> | ENEMY
YOU | MCOMS • ✓-<[O]>-×-×-× • MCOMS | ENEMY

YOU | MCOMS - v-v-<[O]>-x-x - MCOMS | ENEMY
YOU | MCOMS - v-v-v-v-v - <[MCOMS]> | ENEMY
YOU | MCOMS - v-<[O]>-x-x-x - MCOMS | ENEMY

ALLY ► MCOMS | ✓ ✓ [•] × × | MCOMS ◄ ENEMY
ALLY ► MCOMS | ✓ ✓ ✓ ✓ ✓ | <[ MCOMS ]> ◄ ENEMY
ALLY ► MCOMS | ✓ [•] × × × | MCOMS ◄ ENEMY

**Comment by The0zzy** [comment]
YOU | MCOMS ~ •-•-<[•]>-×-× ~ MCOMS | ENEMY
YOU | MCOMS ~ •-•-•-•-• ~ <[ MCOMS ]> | ENEMY
YOU | MCOMS ~ •-<[•]>-×-×-× - MCOMS | ENEMY

**Comment by Manc0ur** [comment]
#1!

**Comment by The0zzy** [comment]
YOU|> MCOMs-1-2-3-4-5-<[MCOMs]> <|ENEMY
YOU|> MCOMs-1-2-<[3]>-4-5-MCOMs <|ENEMY

**Comment by The0zzy** [comment]
YOU ||>   <[MCOMs]>-1-2-3-MCOMs   <|| ENEMY

**Comment by The0zzy** [comment]
I'm fine with the latest: 
YOU ||   <[MCOMs]>-1-2-3-MCOMs   || ENEMY
